CREATE TABLE company (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(150) NOT NULL,
     linkedin_url VARCHAR(255),
     location VARCHAR(150),
     notes TEXT
);

CREATE TABLE technology (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE job_opening (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     title VARCHAR(150) NOT NULL,
     description TEXT,
     level VARCHAR(55),
     work_mode VARCHAR(20) CHECK (work_mode IN ('REMOTE', 'HYBRID', 'ONSITE')),
     job_url VARCHAR(255),
     posted_at DATE,
     company_id BIGINT NOT NULL,
     CONSTRAINT fk_job_opening_company
        FOREIGN KEY (company_id)
        REFERENCES company(id)
);

CREATE TABLE job_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_opening_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (
     status IN ('APPLIED', 'IN_REVIEW', 'INTERVIEW', 'TECHNICAL_TEST', 'APPROVED', 'REJECTED')
     ),
    notes TEXT,
    applied_at DATE NOT NULL,
    CONSTRAINT fk_job_application_job_opening
        FOREIGN KEY (job_opening_id)
        REFERENCES job_opening(id)
);

CREATE TABLE interview (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_application_id BIGINT NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    type VARCHAR(55) NOT NULL CHECK (type IN ('HR', 'TECHNICAL', 'CULTURAL_FIT', 'FINAL')),
    interviewer VARCHAR(150),
    notes TEXT,
    CONSTRAINT fk_interview_job_application
       FOREIGN KEY (job_application_id)
           REFERENCES job_application(id)
);